### ISSUE TITLE
[질문] Multi Process가 왜 더 느린가요?

### ISSUE THREAD

**Issue by ch-4ml** [mjseok/SSAFY_CS_Study#40]
+ Chrome이 multi process를 채택한 이유는 무엇인가요?

**Comment by mjseok** [comment]
프로세스는 스케줄링 대상이므로 멀티프로세스를 사용하면, 문맥교환(컨텍스트스위칭)이 많이 일어나고 이는 오버헤드로 이어집니다. 스레드 또한 스케줄링 대상이고 문맥교환이 발생하지만, 자원을 공유하기 때문에 오버헤드가 프로세스에 비해 적습니다.  
chrome은 각각의 tab이 process-per-tab방식을 사용하고 있는데, 만약 모든 탭들이 동일한 프로세스를 사용한다면 하나의 탭에서 에러가 발생하면 모든 탭에 에러가 발생할 것이기 때문에 멀티프로세스 방식을 채택했습니다.
