### ISSUE TITLE
[질문] Binary semaphore와 Mutex를 동일하게 볼 수 있나요?

### ISSUE THREAD

**Issue by ch-4ml** [mjseok/SSAFY_CS_Study#46]

**Comment by mjseok** [comment]
binary semaphore는 0과 1의 두 가지 값만 가질 수 있는 세마포어입니다.
구현의 측면에서 보면, 둘이 유사하기 때문에 뮤텍스는 바이너리 세마포어라고 할 수 있습니다.
하지만, 메커니즘 측면에서 보면, 동일하게 보기는 어렵습니다. 
뮤텍스는  **잠금 메커니즘** (리소스에 대한 접근을 동기화하는 데 사용되는 메커니즘)
세마포어는  **신호 메커니즘**  (신호를 기반으로 상호 배제가 일어나는 메커니즘)
